import { CommandDescription } from "../types";

export const wpmCmds = [{
  value: 69,
  name: "WM_CMD_NAV_DUBINS",
  description: "Navigate around waypoint via dubins path",
  hasLocation: true,
  isDestination: true,
  parameters: [{
    index: 1,
    label: "Fly-By distance",
    description: "The distance so safely fly pass the waypoint",
    units: "m",
    minValue: 0,
    maxValue: null,
    increment: null,
    default: null,
    options: [],
  }, {
    index: 2,
    label: "Heading",
    description: "The heading to fly through",
    units: "deg",
    minValue: 0,
    maxValue: 360,
    increment: null,
    default: null,
    options: [],
  }, {
    index: 3,
    label: "Radius",
    description: "The turn radius around the waypoint",
    units: "m",
    minValue: 0,
    maxValue: null,
    increment: null,
    default: null,
    options: [],
  }, null, {
    index: 5,
    label: "Latitude",
    description: "Latitude",
    units: "",
    minValue: null,
    maxValue: null,
    increment: null,
    default: null,
    options: [],
  }, {
    index: 6,
    label: "Longitude",
    description: "Longitude",
    units: "",
    minValue: null,
    maxValue: null,
    increment: null,
    default: null,
    options: [],
  }, {
    index: 7,
    label: "Altitude",
    description: "Altitude",
    units: "m",
    minValue: null,
    maxValue: null,
    increment: null,
    default: null,
    options: [],
  }],
}] as const satisfies CommandDescription[]
